master:
  node_id: 1
  driver: "ros2_canopen::MasterNode"
  package: "canopen_core"

motioncontroller_1:
  node_id: 2
  dcf: "pdo.eds"
  driver: "ros2_canopen::ProxyDriver"
  package: "canopen_proxy_driver"
  enable_lazy_load: false
