master:
  node_id: 1
  driver: "ros2_canopen::MasterNode"
  package: "canopen_core"

motioncontroller_2:
  node_id: 2
  dcf: "simple.eds"
  driver: "ros2_canopen::ProxyDriver"
  package: "canopen_proxy_driver"
  enable_lazy_load: false

motioncontroller_3:
  node_id: 3
  dcf: "simple.eds"
  driver: "ros2_canopen::ProxyDriver"
  package: "canopen_proxy_driver"
  enable_lazy_load: false

motioncontroller_4:
  node_id: 4
  dcf: "simple.eds"
  driver: "ros2_canopen::ProxyDriver"
  package: "canopen_proxy_driver"
  enable_lazy_load: false

motioncontroller_5:
  node_id: 5
  dcf: "simple.eds"
  driver: "ros2_canopen::ProxyDriver"
  package: "canopen_proxy_driver"
  enable_lazy_load: false

motioncontroller_6:
  node_id: 6
  dcf: "simple.eds"
  driver: "ros2_canopen::ProxyDriver"
  package: "canopen_proxy_driver"
  enable_lazy_load: false

motioncontroller_7:
  node_id: 7
  dcf: "simple.eds"
  driver: "ros2_canopen::ProxyDriver"
  package: "canopen_proxy_driver"
  enable_lazy_load: false

#motioncontroller_8:
#  node_id: 8
#  dcf: "simple.eds"
#  driver: "ros2_canopen::ProxyDriver"
#  package: "canopen_proxy_driver"
#
#motioncontroller_9:
#  node_id: 9
#  dcf: "simple.eds"
#  driver: "ros2_canopen::ProxyDriver"
#  package: "canopen_proxy_driver"
#
#motioncontroller_10:
#  node_id: 10
#  dcf: "simple.eds"
#  driver: "ros2_canopen::ProxyDriver"
#  package: "canopen_proxy_driver"
#
#motioncontroller_11:
#  node_id: 11
#  dcf: "simple.eds"
#  driver: "ros2_canopen::ProxyDriver"
#  package: "canopen_proxy_driver"
#
#motioncontroller_12:
#  node_id: 12
#  dcf: "simple.eds"
#  driver: "ros2_canopen::ProxyDriver"
#  package: "canopen_proxy_driver"
#
#motioncontroller_13:
#  node_id: 13
#  dcf: "simple.eds"
#  driver: "ros2_canopen::ProxyDriver"
#  package: "canopen_proxy_driver"
#
#motioncontroller_14:
#  node_id: 14
#  dcf: "simple.eds"
#  driver: "ros2_canopen::ProxyDriver"
#  package: "canopen_proxy_driver"
#
#motioncontroller_15:
#  node_id: 15
#  dcf: "simple.eds"
#  driver: "ros2_canopen::ProxyDriver"
#  package: "canopen_proxy_driver"
#
#motioncontroller_16:
#  node_id: 16
#  dcf: "simple.eds"
#  driver: "ros2_canopen::ProxyDriver"
#  package: "canopen_proxy_driver"
#
#motioncontroller_17:
#  node_id: 17
#  dcf: "simple.eds"
#  driver: "ros2_canopen::ProxyDriver"
#  package: "canopen_proxy_driver"
#
#motioncontroller_18:
#  node_id: 18
#  dcf: "simple.eds"
#  driver: "ros2_canopen::ProxyDriver"
#  package: "canopen_proxy_driver"
#
#motioncontroller_19:
#  node_id: 19
#  dcf: "simple.eds"
#  driver: "ros2_canopen::ProxyDriver"
#  package: "canopen_proxy_driver"
#
#motioncontroller_20:
#  node_id: 20
#  dcf: "simple.eds"
#  driver: "ros2_canopen::ProxyDriver"
#  package: "canopen_proxy_driver"