name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_documentation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
            sudo apt-get update -qq
            sudo apt-get install -y -qq doxygen graphviz
            pip install sphinx-rtd-theme
            pip install sphinx-mdinclude
            pip install breathe
            pip install exhale

      
      - name: Build documentation
        uses: sphinx-notes/pages@2.0
        with:
          # Relative path under $repository_path to documentation source files
          documentation_path: ./canopen/sphinx/
          target_branch: gh-pages

      - name: Push documentation to gh-pages
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
      
