master:
  node_id: 1
  driver: "ros2_canopen::MasterNode"
  package: "canopen_core"

canopen_proxy_driver:
  node_id: 2
  dcf: "simple.eds"
  driver: "ros2_canopen::ProxyDriver"
  package: "canopen_proxy_driver"
  enable_lazy_load: false
